import type { Metadata } from "next";
import "./globals.css";
import { montserrat, roboto, nunito, doto } from "@/lib/font";

export const metadata: Metadata = {
  title: "Hiree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`antialiased ${montserrat.variable} ${roboto.variable} ${nunito.variable} ${doto.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
